### ISSUE TITLE
using with swagger-ui-express, trying to figure out how to handle the promise

### ISSUE THREAD

**Issue by travis5491811** [James-Messinger/swagger-parser#95]
Hello,

This tool works great. This issue isn't exactly about the tool. I'm trying to get help using the tool in a work flow.  I added it to my express API and I'm having trouble understanding what i might be missing with handling promise. I'm having trouble with an issue similar to [this](https://stackoverflow.com/questions/41364072/running-an-async-function-before-express-js-start?rq=1).

In my case, i need `swagger-parser` `dereference` to finish before i call `  app.use('/apidocs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));`

In the solution above, i have to send a promise to everything that imports app.js. The rabbit hole is getting deep because in this big app, a lot of stuff is importing from app and I'm having to wrap all those things in `.then..` calls. 

I get the point of promises is to not block functions, but in this use case, I do want to block the app from starting before this is finished but not at the consequence of making everything connected to app a promise. The other thing i though about figuring out how to do is when i do `npm run dev' and it watches my files for changes with `nodemon` somehow tell it to run the `swagger-cli` before starting or restarting the app. I'm not sure if this is possible.

Is there a way around this?

One work around is using `swagger-cli` instead, but i wan't able to get this working in a way where `nodemon` would restart the app after the yaml file was being generated. Part of my `package.json`:

```
  "scripts": {
    "dev": "NODE_ENV=development DEBUG=CUSTOM-DEBUG* nodemon --inspect ./bin/www",
    "parseSwaggerDocs": "node_modules/swagger-cli/bin/swagger-cli.js bundle ./test/integration_test/openapi/global.yml -o ./openapi.yml -t yaml"
}
```

**Comment by James-Messinger** [comment]
You can start your app after `dereference()` is done like this...

```javascript
swaggerParser.dereference('my-api.yaml').then(startMyApp);

function startMyApp(swaggerSpec) {
    let app = express();
    app.use('/apidocs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
    app.listen(8080);
}
```
